---
- include_tasks: config.yml

- include_tasks: clone.yml
  when:
    - keystone_dev_mode | bool

- include_tasks: bootstrap.yml

- name: Flush handlers
  meta: flush_handlers

- include_tasks: init_fernet.yml
  when:
    - keystone_token_provider == 'fernet'

- include_tasks: register.yml

- include_tasks: check.yml

- include_tasks: register_identity_providers.yml
  when:
    - keystone_identity_providers is defined
    - keystone_identity_providers is not none
    - identity_provider_attribute_mappings is defined
    - identity_provider_attribute_mappings is not none
