---
k3s_services:
  k3s:
    container_name: k3s
    group: k3s
    enabled: true
    image: "{{ k3s_image_full }}"
    volumes: "{{ k3s_default_volumes + k3s_extra_volumes }}"
    privileged: true
    haproxy:
      k3s:
        enabled: "{{ enable_k3s }}"
        mode: "tcp"
        external: false
        port: "{{ k3s_port }}"
        listen_port: "{{ k3s_listen_port }}"
      k3s_external:
        enabled: "{{ enable_k3s }}"
        mode: "tcp"
        external: true
        port: "{{ k3s_port }}"
        listen_port: "{{ k3s_listen_port }}"


####################
# Docker
####################
k3s_install_type: "{{ kolla_install_type }}"
k3s_tag: "{{ openstack_tag }}"
k3s_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ k3s_install_type }}-k3s"
k3s_image_full: "{{ k3s_image }}:{{ k3s_tag }}"

k3s_default_volumes:
  - "{{ node_config_directory }}/k3s/:{{ container_config_directory }}/:ro"
  - "/etc/localtime:/etc/localtime:ro"
  - "/etc/machine-id:/etc/machine-id:ro"
  - "{{ '/etc/timezone:/etc/timezone:ro' if ansible_os_family == 'Debian' else '' }}"
  - "kolla_logs:/var/log/kolla"
  - "k3s_server:/var/lib/rancher/k3s"

k3s_extra_volumes: "{{ default_extra_volumes }}"

# entries in this dict get templated into k3s.yaml
# https://docs.k3s.io/installation/configuration#configuration-file
k3s_config:
  log: /var/log/kolla/k3s/k3s.log
  tls-san: "{{ kolla_internal_vip_address }}"
  bind-address: "{{ api_interface_address }}"
  node-ip: "{{ api_interface_address }}"
  token: "{{ k3s_token }}"
  write-kubeconfig-mode: "0644"
  write-kubeconfig: "/root/.kube/config"  
  cluster-cidr: "192.168.0.0/16"
  cluster-init: true
  flannel-backend: "none"
  disable-network-policy: true
  disable:
    - traefik
