---

- import_tasks: config.yml

- import_tasks: check-containers.yml

- name: Flush handlers
  meta: flush_handlers

# Need to run these tasks after k3s api server has started
- import_tasks: post_config.yml
