---
- name: Creating clouds.yaml file on the deploy node
  hosts: localhost
  tasks:
    - name: Create /etc/openstack directory
      become: true
      file:
        state: directory
        dest: "/etc/openstack"
        owner: "{{ ansible_facts.user_uid }}"
        group: "{{ ansible_facts.user_gid }}"
        mode: 0700

    - name: Template out clouds.yaml
      become: true
      template:
        src: "roles/common/templates/clouds.yaml.j2"
        dest: "{{ node_config }}/clouds.yaml"
        owner: "{{ ansible_facts.user_uid }}"
        group: "{{ ansible_facts.user_gid }}"
        mode: 0600

- name: Creating admin openrc file on the deploy node
  hosts: localhost
  tasks:
    - name: Template out admin-openrc.sh
      template:
        src: "roles/common/templates/admin-openrc.sh.j2"
        dest: "{{ admin_openrc_directory }}/admin-openrc.sh"
        owner: "{{ ansible_facts.user_uid }}"
        group: "{{ ansible_facts.user_gid }}"
        mode: 0600

    - import_role:
        name: octavia
        tasks_from: openrc.yml
      when: enable_octavia | bool

- import_playbook: "{{ post_deploy_extra_play }}"
  when: post_deploy_extra_play is defined
